# -*- coding: utf-8 -*-
"""app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1HZhsRihGI4xXdqUTM8zRstrlgaJ7dLLk
"""

from fastapi import FastAPI, UploadFile, File
import shutil

from model import MedicalClassifier

app = FastAPI(
    title="Medical Image Classification API"
)

classifier = MedicalClassifier()


@app.post("/predict")
async def predict(image: UploadFile = File(...)):

    path = image.filename

    with open(path, "wb") as buffer:
        shutil.copyfileobj(image.file, buffer)

    result = classifier.predict(path)

    return result