# -*- coding: utf-8 -*-
"""model.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1HZhsRihGI4xXdqUTM8zRstrlgaJ7dLLk
"""

import torch
import torch.nn as nn
from torchvision import models, transforms
from PIL import Image

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")


class MedicalClassifier:

    def __init__(self):

        self.model = models.resnet50(weights=None)

        self.model.fc = nn.Linear(
            self.model.fc.in_features,
            2
        )

        self.model.load_state_dict(
            torch.load(
                "medical_model.pth",
                map_location=device
            )
        )

        self.model.to(device)
        self.model.eval()

        self.transform = transforms.Compose([
            transforms.Resize((224, 224)),
            transforms.ToTensor()
        ])

        self.classes = [
            "NORMAL",
            "PNEUMONIA"
        ]

    def predict(self, image_path):

        image = Image.open(image_path).convert("RGB")

        image = self.transform(image)

        image = image.unsqueeze(0).to(device)

        with torch.no_grad():

            outputs = self.model(image)

            probabilities = torch.softmax(outputs, dim=1)

            confidence, prediction = torch.max(
                probabilities,
                dim=1
            )

        return {
            "prediction": self.classes[prediction.item()],
            "confidence": round(confidence.item(), 4)
        }