# -*- coding: utf-8 -*-
"""test_api.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1HZhsRihGI4xXdqUTM8zRstrlgaJ7dLLk
"""

from fastapi.testclient import TestClient

from app import app

client = TestClient(app)


def test_predict():

    with open(
        "sample_images/normal.jpg",
        "rb"
    ) as image:

        response = client.post(
            "/predict",
            files={
                "image": (
                    "normal.jpg",
                    image,
                    "image/jpeg"
                )
            }
        )

    assert response.status_code == 200